name: Build and Release Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    if: contains(github.event.head_commit.message, '#release')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install .[exe]

      - name: Build executable
        run: pyinstaller --onefile --windowed --distpath . key_remap.py

      - name: List downloaded files (Debugging)
        run: ls -R

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: key_remap.exe
  tag:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag_name: ${{ steps.tag.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - id: tag
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  release:
    needs: tag
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: List downloaded files (Debugging)
        run: ls -R

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.tag.outputs.tag_name }}
          files: |
            key_remap.exe